import type { Context } from "hono";
import { Session } from "./middleware/auth";

// Note: The Env interface is generated by wrangler in worker-configuration.d.ts
// It includes all D1 databases, SecretsStoreSecret bindings, Queue bindings, etc.
// Do NOT redeclare Env here as it will conflict with the generated types.

// Define context variables that can be set/get
type Variables = {
  session: Session;
  org_id?: string;
};

export type AppContext = Context<{
  Bindings: Env;
  Variables: Variables;
}>;

export type HandleArgs = [AppContext];
