import type { Context } from "hono";
import { Session } from "./middleware/auth";

// Note: The Env interface is generated by wrangler in worker-configuration.d.ts
// It includes all D1 databases, SecretsStoreSecret bindings, Queue bindings, etc.
// Do NOT redeclare Env here as it will conflict with the generated types.

// =============================================================================
// Common Status Types
// Mirror of clearlift-cron/shared/types/index.ts - keep in sync
// =============================================================================

/**
 * Generic job/task status for sync jobs, analysis jobs, etc.
 * Use this for any async operation that progresses through these states.
 */
export type JobStatus = 'pending' | 'running' | 'completed' | 'failed';

/**
 * Array form of JobStatus for use in validation schemas.
 */
export const JOB_STATUS_VALUES = ['pending', 'running', 'completed', 'failed'] as const;

/**
 * Alias for connector sync status (same as JobStatus).
 */
export type SyncStatus = JobStatus;

// Define context variables that can be set/get
type Variables = {
  session: Session;
  org_id?: string;
};

export type AppContext = Context<{
  Bindings: Env;
  Variables: Variables;
}>;

export type HandleArgs = [AppContext];

/**
 * Data Setup Status - Used across analytics endpoints to communicate
 * what's missing and provide actionable guidance to users.
 */
export interface SetupStatus {
  hasTrackingTag: boolean;
  hasAdPlatforms: boolean;
  hasRevenueConnector: boolean;
  hasClickIds: boolean;
  hasUtmData: boolean;
  trackingDomain?: string;
  shortTag?: string;
  connectedPlatforms: string[];
  connectedConnectors: string[];
}

/**
 * Data Quality Response - Consistent empty state handling across all analytics endpoints.
 * When data is missing, this explains WHY and HOW to fix it.
 */
export interface DataQualityResponse {
  /** Current data quality level */
  quality: 'complete' | 'partial' | 'limited' | 'none';
  /** What's currently set up */
  setup: SetupStatus;
  /** Human-readable issues */
  issues: string[];
  /** Actionable recommendations */
  recommendations: {
    action: string;
    description: string;
    setupUrl: string;
    priority: 'high' | 'medium' | 'low';
  }[];
  /** Percentage of data completeness (0-100) */
  completeness: number;
}

/**
 * Helper to build consistent data quality responses
 */
export function buildDataQualityResponse(setup: SetupStatus): DataQualityResponse {
  const issues: string[] = [];
  const recommendations: DataQualityResponse['recommendations'] = [];

  // Check tracking tag
  if (!setup.hasTrackingTag) {
    issues.push('No tracking tag configured');
    recommendations.push({
      action: 'Install tracking tag',
      description: 'Add the ClearLift tracking tag to your website to capture visitor journeys and UTM parameters.',
      setupUrl: '/settings?tab=tracking',
      priority: 'high'
    });
  }

  // Check ad platforms
  if (!setup.hasAdPlatforms) {
    issues.push('No ad platforms connected');
    recommendations.push({
      action: 'Connect ad platforms',
      description: 'Connect Google Ads, Meta Ads, or TikTok Ads to import spend and campaign data.',
      setupUrl: '/connectors',
      priority: 'high'
    });
  }

  // Check revenue connector
  if (!setup.hasRevenueConnector) {
    issues.push('No revenue source connected');
    recommendations.push({
      action: 'Connect revenue source',
      description: 'Connect Stripe, Shopify, or Jobber to track actual conversions and revenue.',
      setupUrl: '/connectors',
      priority: 'high'
    });
  }

  // Check UTM data (only if tag is installed)
  if (setup.hasTrackingTag && !setup.hasUtmData) {
    issues.push('No UTM parameters detected');
    recommendations.push({
      action: 'Add UTM parameters to ad campaigns',
      description: 'Your tracking tag is installed but no UTM data is being captured. Ensure your ad campaigns include UTM parameters.',
      setupUrl: '/settings?tab=tracking',
      priority: 'medium'
    });
  }

  // Check click IDs (only if platforms connected)
  if (setup.hasAdPlatforms && !setup.hasClickIds) {
    issues.push('No click IDs captured (gclid/fbclid/ttclid)');
    recommendations.push({
      action: 'Enable auto-tagging',
      description: 'Enable auto-tagging in your ad platforms to capture click IDs for 100% accurate attribution.',
      setupUrl: '/settings?tab=tracking',
      priority: 'medium'
    });
  }

  // Calculate completeness
  const checkpoints = [
    setup.hasTrackingTag,
    setup.hasAdPlatforms,
    setup.hasRevenueConnector,
    setup.hasUtmData,
    setup.hasClickIds
  ];
  const completeness = Math.round((checkpoints.filter(Boolean).length / checkpoints.length) * 100);

  // Determine quality level
  let quality: DataQualityResponse['quality'];
  if (completeness >= 80) {
    quality = 'complete';
  } else if (completeness >= 60) {
    quality = 'partial';
  } else if (completeness >= 20) {
    quality = 'limited';
  } else {
    quality = 'none';
  }

  return {
    quality,
    setup,
    issues,
    recommendations,
    completeness
  };
}
